name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Add timeout to prevent hanging builds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # For faster, more efficient builds

      - name: Build Docker Image
        run: docker build --cache-from=ghcr.io/${{ github.repository }}/pdf-scraper:latest -t ghcr.io/${{ github.repository }}/pdf-scraper:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/pdf-scraper:latest
