name: Daily PDF Scraper Run

on:
  schedule:
    - cron: "30 11 * * *" # 11:30 AM UTC = 5:00 PM IST
  workflow_dispatch: # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Add timeout for the job

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run Docker Container from Registry
        run: |
          docker pull ghcr.io/${{ github.repository }}/pdf-scraper:latest
          docker run --rm \
            --memory=1g \
            -e NEWSPAPER_BASE_URL="${{ secrets.NEWSPAPER_BASE_URL }}" \
            -e SLACK_BOT_TOKEN="${{ secrets.SLACK_BOT_TOKEN }}" \
            -e SLACK_CHANNEL_ID="${{ secrets.SLACK_CHANNEL_ID }}" \
            ghcr.io/${{ github.repository }}/pdf-scraper:latest
        timeout-minutes: 15 # Add a step-specific timeout
